module Zuora
  module Objects
  end
end

require 'zuora/objects/base'
require 'zuora/objects/account'
require 'zuora/objects/contact'
require 'zuora/objects/amendment'
require 'zuora/objects/communication_profile'
require 'zuora/objects/credit_balance_adjustment'
require 'zuora/objects/invoice'
require 'zuora/objects/invoice_adjustment'
require 'zuora/objects/invoice_item'
require 'zuora/objects/invoice_item_adjustment'
require 'zuora/objects/invoice_payment'
require 'zuora/objects/usage'
require 'zuora/objects/subscribe_request'
require 'zuora/objects/subscription'
require 'zuora/objects/payment'
require 'zuora/objects/payment_method'
require 'zuora/objects/product'
require 'zuora/objects/product_rate_plan'
require 'zuora/objects/product_rate_plan_charge'
require 'zuora/objects/product_rate_plan_charge_tier'
require 'zuora/objects/rate_plan'
require 'zuora/objects/rate_plan_data'
require 'zuora/objects/rate_plan_charge'
require 'zuora/objects/rate_plan_charge_data'
require 'zuora/objects/rate_plan_charge_tier'
require 'zuora/objects/refund'
require 'zuora/objects/refund_invoice_payment'
