module Zuora
  module Objects
    autoload :Base,                      'zuora/objects/base'
    autoload :Account,                   'zuora/objects/account'
    autoload :Contact,                   'zuora/objects/contact'
    autoload :Amendment,                 'zuora/objects/amendment'
    autoload :CommunicationProfile,      'zuora/objects/communication_profile'
    # autoload :CreditBalanceAdjustment,   'zuora/objects/credit_balance_adjustment'
    autoload :Invoice,                   'zuora/objects/invoice'
    autoload :InvoiceAdjustment,         'zuora/objects/invoice_adjustment'
    autoload :InvoiceItem,               'zuora/objects/invoice_item'
    autoload :InvoiceItemAdjustment,     'zuora/objects/invoice_item_adjustment'
    # autoload :InvoicePayment,            'zuora/objects/invoice_payment'
    autoload :Usage,                     'zuora/objects/usage'
    autoload :SubscribeRequest,          'zuora/objects/subscribe_request'
    autoload :Subscription,              'zuora/objects/subscription'
    # autoload :Payment,                   'zuora/objects/payment'
    autoload :PaymentMethod,             'zuora/objects/payment_method'
    autoload :Product,                   'zuora/objects/product'
    autoload :ProductRatePlan,           'zuora/objects/product_rate_plan'
    autoload :ProductRatePlanCharge,     'zuora/objects/product_rate_plan_charge'
    autoload :ProductRatePlanChargeTier, 'zuora/objects/product_rate_plan_charge_tier'
    autoload :RatePlan,                  'zuora/objects/rate_plan'
    autoload :RatePlanCharge,            'zuora/objects/rate_plan_charge'
    autoload :RatePlanChargeTier,        'zuora/objects/rate_plan_charge_tier'
    # autoload :Refund,                    'zuora/objects/refund'
  end
end
